/** Base curated club facts */
const CURATED_CLUB_FACTS = [
  { match: 'egypt', facts: [
    'Egypt has won a record 7 Africa Cup of Nations titles - more than any other nation.',
    'The Pharaohs were the first African team to play at a FIFA World Cup, in 1934.',
    'Egypt reached the AFCON final in 2021 and 2022, showing their continued dominance.',
    'Mohamed Salah is the most famous modern Pharaoh and one of the world\'s best forwards.',
    'Hossam Hassan is Egypt\'s all-time top scorer with over 70 international goals.',
    'The national team plays in red kits with the iconic eagle crest.',
    'Egypt hosted and won AFCON tournaments in 1957, 1959, 1986, 1998, 2006, 2008, and 2010.',
    'The Cairo International Stadium is among the venues used for major national team matches.',
    'Egypt has produced legends like Mohamed Aboutrika, Ahmed Hassan, and Essam El-Hadary.',
    'The Pharaohs are perennial favourites every time AFCON comes around.',
    'Egypt\'s passionate supporters fill stadiums across the country for home qualifiers.',
    'The national team represents over 100 million football-mad Egyptians worldwide.',
    'Egypt finished 2nd in World Cup 2026 Group G and qualified for the Round of 32.',
    'Next up for the Pharaohs: Australia in the Round of 32 - beat them and Egypt face Argentina in the Round of 16.',
  ]},
  { match: 'ahly', facts: [
    'Al Ahly are the most successful club in CAF Champions League history.',
    'Nicknamed "The Red Devils", Ahly were founded in 1907 in Cairo.',
    'The Cairo Derby against Zamalek is one of the fiercest rivalries in world football.',
    'Ahly have won the Egyptian Premier League more times than any other club.',
    'The club plays at the iconic Cairo International Stadium for many big matches.',
    'Ahly fans are known for creating incredible atmospheres with red flares and chants.',
    'The club has won multiple CAF Super Cup titles.',
    'Ahly\'s youth academy has produced countless Egyptian internationals.',
    'Aboutrika, Barakat, and El-Shahat are among Ahly\'s most beloved legends.',
    'Ahly regularly compete in the CAF Champions League knockout stages.',
    'The club\'s badge features the red devil symbol recognised across Africa.',
    'Ahly hold the record for most Egyptian Cup victories.',
  ]},
  { match: 'zamalek', facts: [
    'Zamalek are known as "The White Knights" and were founded in 1911.',
    'Zamalek share Cairo with rivals Al Ahly in the famous Cairo Derby.',
    'The club has won multiple Egyptian Premier League championships.',
    'Zamalek claimed CAF Confederation Cup glory in 2019.',
    'The White Knights play at the Cairo International Stadium.',
    'Zamalek have one of the largest and most passionate fanbases in Egypt.',
    'The club\'s white kit is instantly recognisable across African football.',
    'Zamalek have produced stars like Shikabala, Fawzy, and Hassan Shehata as a player.',
    'Derby day in Cairo stops the city as millions watch Ahly vs Zamalek.',
    'Zamalek have won the Egyptian Cup numerous times throughout their history.',
    'The club competed in the FIFA Club World Cup after continental success.',
    'Zamalek\'s ultras are famous for choreographed displays in the stands.',
  ]},
  { match: 'pyramids', facts: [
    'Pyramids FC rose quickly after major investment in the late 2010s.',
    'The club play at the 30 June Stadium in Cairo.',
    'Pyramids have finished near the top of the Egyptian Premier League table.',
    'The club signed high-profile players to challenge Ahly and Zamalek.',
    'Pyramids FC rebranded from their previous identity to build a new brand.',
    'The club has modern training facilities compared to many Egyptian sides.',
    'Pyramids have competed in CAF continental competitions.',
    'The name references Egypt\'s ancient pyramids, tying the club to national identity.',
    'Pyramids have been one of the biggest spenders in Egyptian football.',
    'The club aims to break the traditional duopoly of Ahly and Zamalek.',
  ]},
  { match: 'ismaily', facts: [
    'Ismaily SC are based in Ismailia on the Suez Canal.',
    'Nicknamed "The Yellow Dragons", Ismaily wear distinctive yellow kits.',
    'Ismaily won the CAF Champions League in 1969 - a historic achievement.',
    'The club has won the Egyptian Premier League multiple times.',
    'Ismaily Stadium is their fortress in the canal city.',
    'Ismaily have a fierce regional following in the Suez Canal zone.',
    'The club produced talented players who starred for the national team.',
    'Ismaily\'s golden era in the 1960s and 70s is still celebrated today.',
    'The Yellow Dragons remain one of Egypt\'s most historic clubs.',
    'Matches against Cairo giants always draw huge canal-city crowds.',
  ]},
  { match: 'smouha', facts: [
    'Smouha SC are based in Alexandria, Egypt\'s second-largest city.',
    'The club was founded in 1949 and plays at Smouha Stadium.',
    'Smouha are known for developing young Egyptian talent.',
    'The club has been a consistent Egyptian Premier League presence.',
    'Alexandria\'s coastal culture influences Smouha\'s passionate support.',
    'Smouha have competed in the Egyptian Cup knockout rounds regularly.',
    'The club\'s blue colours represent their Alexandria identity.',
    'Smouha have challenged bigger clubs in cup upsets over the years.',
    'The academy pipeline feeds players into the first team and national side.',
    'Smouha matches draw strong local crowds from across Alexandria.',
  ]},
  { match: 'gouna', facts: [
    'El Gouna FC represent the Red Sea resort town of El Gouna.',
    'The club offers a unique coastal setting in Egyptian football.',
    'El Gouna have competed in the Egyptian Premier League.',
    'The resort backing gives the club a distinctive identity.',
    'El Gouna Stadium hosts home matches near the Red Sea.',
    'The club has worked to establish itself among Egypt\'s top flight.',
    'El Gouna\'s location attracts visitors who discover Egyptian league football.',
    'The club has invested in squad building to avoid relegation battles.',
    'Red Sea communities rally behind El Gouna on matchdays.',
    'El Gouna represent tourism and sport combined in one club.',
  ]},
  { match: 'ceramica', facts: [
    'Ceramica Cleopatra FC were formed through merger and rebranding in 2020.',
    'The club plays at the New Suez Stadium.',
    'Ceramica reached the Egyptian Premier League remarkably quickly.',
    'Heavy investment helped build a competitive squad fast.',
    'The Ceramica name comes from the sponsoring ceramics company.',
    'Cleopatra in the name ties the club to Egyptian heritage.',
    'The club has aimed to establish itself as a top-tier regular.',
    'Ceramica Cleopatra have been active in the transfer market.',
    'Suez region fans have embraced the new club identity.',
    'The club represents modern corporate-backed football in Egypt.',
  ]},
  { match: 'pharco', facts: [
    'Pharco FC are based in Alexandria.',
    'The club is backed by the Pharco pharmaceutical group.',
    'Pharco play at the Alexandria Stadium.',
    'The club climbed through divisions to reach the top flight.',
    'Pharco\'s rise shows how investment can transform Egyptian clubs.',
    'Alexandria fans have welcomed another Premier League side.',
    'The club name references Egypt\'s ancient pharaohs.',
    'Pharco have focused on building a stable squad in the top division.',
    'The pharmaceutical backing provides financial stability.',
    'Pharco compete against Smouha and other Alexandria-area rivals.',
  ]},
  { match: 'national bank', facts: [
    'National Bank of Egypt FC reached the Premier League in 2021.',
    'The club is linked to Egypt\'s national banking institution.',
    'NBE FC play home matches in Cairo.',
    'Promotion was a major achievement for the banking-backed side.',
    'The club has focused on gradual squad improvement.',
    'NBE represent institutional investment in Egyptian football.',
    'The team has worked to secure their top-flight status.',
    'Young Egyptian players get opportunities at NBE.',
    'The club\'s green branding reflects the bank\'s identity.',
    'NBE matches are part of Cairo\'s busy football calendar.',
  ]},
  { match: 'masry', facts: [
    'Al Masry SC are based in Port Said on the Mediterranean.',
    'Nicknamed "The Green Eagles", Al Masry wear green kits.',
    'Port Said Stadium is one of Egypt\'s most atmospheric venues.',
    'Al Masry have a fierce fanbase in the Suez Canal region.',
    'The club has been a regular Premier League presence.',
    'Port Said\'s football culture is among the most passionate in Egypt.',
    'Al Masry have caused upsets against Cairo giants in cups.',
    'The Green Eagles represent canal-city pride.',
    'Al Masry\'s history stretches back decades in Egyptian football.',
    'Away trips to Port Said are daunting for visiting teams.',
  ]},
  { match: 'mokawloon', facts: [
    'Arab Contractors SC (Al Mokawloon) are a historic Cairo club.',
    'The club was founded in 1973.',
    'Al Mokawloon play at the Arab Contractors Stadium.',
    'The club has produced many Egyptian internationals over the years.',
    'Arab Contractors have won domestic honours in Egypt.',
    'The club is linked to Egypt\'s construction industry.',
    'Mokawloon have yo-yoed between divisions but remain respected.',
    'Their academy has developed technically gifted players.',
    'Cairo derbies against bigger clubs are always competitive.',
    'Al Mokawloon\'s green kit is recognisable in the league.',
  ]},
  { match: 'enppi', facts: [
    'ENPPI FC are based in Cairo and linked to the petroleum industry.',
    'The club is famous for its youth academy pipeline.',
    'ENPPI have won the Egyptian Premier League.',
    'Many ENPPI graduates became national team regulars.',
    'The club plays at Petrosport Stadium.',
    'ENPPI focus on developing talent before selling to bigger clubs.',
    'The petroleum backing provides structure and resources.',
    'ENPPI have competed in CAF competitions.',
    'The club\'s model influences other Egyptian sides.',
    'Technical, youthful football is ENPPI\'s trademark.',
  ]},
  { match: 'future', facts: [
    'Future FC are among the newer clubs in the Egyptian Premier League.',
    'The club has invested in reaching and staying in the top flight.',
    'Future FC aim to build a modern club structure.',
    'The name signals ambition for long-term success.',
    'Future have been active in the transfer market.',
    'The club represents new ownership in Egyptian football.',
    'Future FC matches add variety to the league fixture list.',
    'The squad blends experienced and young Egyptian players.',
    'Future are working to grow their fanbase.',
    'Every season is a step toward establishing the club\'s identity.',
  ]},
  { match: 'baladiyat', facts: [
    'Baladiyat El Mahalla represent El Mahalla El Kubra in the Nile Delta.',
    'The city is one of Egypt\'s major industrial centres.',
    'The club has strong local support in the Delta region.',
    'Baladiyat compete in Egypt\'s league pyramid.',
    'El Mahalla has a proud working-class football tradition.',
    'The club name means "Municipality of El Mahalla".',
    'Delta derbies bring intense local rivalry.',
    'Baladiyat\'s fans are known for loyalty through every division.',
    'The club represents community football far from Cairo.',
    'El Mahalla\'s textile industry history ties to the club\'s roots.',
  ]},
];

