/**
 * Extra curated facts — Egyptian Football Facts
 * Merged into CURATED_CLUB_FACTS / Did You Know / club pages.
 */
const EXTRA_CLUB_FACTS = [
  { match: 'egypt', facts: [
    'Egypt were AFCON champions three times in a row: 2006, 2008, and 2010.',
    'Egypt won the first Africa Cup of Nations ever held, in 1957 in Sudan.',
    'Essam El-Hadary is one of the oldest players to appear at a FIFA World Cup.',
    'Mohamed Salah scored Egypt\'s only goal at the 2018 World Cup, from the penalty spot against Russia.',
    'Egypt\'s 2006–2010 AFCON run is widely called the greatest in African football history.',
    'Ahmed Hassan captained Egypt to AFCON glory and earned over 180 caps.',
    'Egypt\'s nickname "The Pharaohs" links the team to ancient Egyptian history.',
    'Cairo International Stadium opened in 1960 and has hosted AFCON finals.',
    'Egypt failed to qualify for the World Cup for decades before returning in 1990.',
    'The Pharaohs reached the 2018 World Cup in Russia after a dramatic playoff vs Congo.',
    'Egypt\'s 3–1 win over Algeria in 1989 is still talked about by older fans.',
    'Hassan Shehata coached Egypt to three straight AFCON titles.',
    'Egypt\'s home crowd at Borg El Arab can create one of Africa\'s loudest atmospheres.',
    'Mohamed Aboutrika was named CAF African Footballer of the Year in 2008.',
    'Egypt have never won a World Cup knockout match — until 2026 they aim to change that.',
    'The Egyptian Football Association was founded in 1921.',
    'Egypt joined FIFA in 1923, among the earliest African members.',
    'Salah\'s goals for Liverpool made him a global icon for Egyptian football.',
    'Egypt\'s red home kit is inspired by the national flag.',
    'The Pharaohs once went undefeated for long stretches under Shehata.',
    'Egypt hosted AFCON 2006 and won it on home soil.',
    'Hossam Hassan scored in multiple AFCON tournaments across different decades.',
    'Egypt\'s rivalry with Algeria is one of the fiercest in African football.',
    'The team\'s eagle crest appears on every official national kit.',
    'Egypt finished top of their 2018 World Cup qualifying group ahead of Uganda and Ghana.',
    'Wael Gomaa was a defensive rock during Egypt\'s three-peat AFCON era.',
    'Egypt\'s midfield legends include Aboutrika, Barakat, and Hassan.',
    'Millions of Egyptians watch every Pharaohs match on cafés screens across the country.',
    'Egypt\'s 7 AFCON titles remain an unbroken continental record.',
    'The national anthem before kickoff often brings tears in Egyptian stadiums.',
    'Egypt played in the 1934 World Cup in Italy — their first finals appearance.',
    'Goalkeeper Ahmed El Shenawy has been a long-time Pharaohs option.',
    'Egypt\'s attacking style under different coaches has swung between possession and counter.',
    'The Pharaohs\' away following travels across Africa for AFCON and World Cup qualifiers.',
    'Egypt\'s youth teams have won African titles and fed talent to Europe.',
    'Mohamed Elneny has represented Egypt at major tournaments while playing in Europe.',
    'Egypt\'s penalty shootout wins at AFCON became part of national folklore.',
    'The 2010 AFCON final win sealed Egypt\'s historic three-peat.',
    'Egypt\'s football culture mixes Cairo derbies with national-team fever.',
    'Every World Cup cycle, Egypt fans dream of a deep knockout run.',
    'Egypt\'s 2026 Group G finish of 2nd put them into the Round of 32.',
    'A win over Australia in 2026 would set up a Round of 16 clash with Argentina.',
    'Egypt\'s World Cup 2026 campaign put the Pharaohs back on the global stage.',
    'Trezeguet and Salah formed a dangerous Egypt attack in recent years.',
    'Egypt\'s defensive organisation was key to reaching knockout stages.',
    'The Pharaohs train at facilities near Cairo before major tournaments.',
    'Egypt\'s kit suppliers have changed over decades, but red remains constant.',
    'Local leagues feed the national team with Ahly, Zamalek, and Pyramids stars.',
    'Egypt\'s captaincy has passed from Hassan to Aboutrika to Salah eras.',
    'Fans call big Pharaohs wins "nights the whole country doesn\'t sleep".',
    'Egypt\'s AFCON dominance made them Africa\'s most feared team for years.',
    'The national team\'s medical and performance staff grew more modern in the 2020s.',
    'Egypt often rotate venues between Cairo and Alexandria for home qualifiers.',
    'Street football in Egypt produces creative players who later wear the red shirt.',
    'Egypt\'s World Cup songs and chants trend nationwide before every finals match.',
    'A Pharaohs goal at a World Cup can stop traffic in Cairo and Alexandria.',
    'Egypt\'s all-time caps leaders include Ahmed Hassan and Ahmed Fathy.',
    'The team\'s mascot culture and fan art explode during tournament summers.',
    'Egypt\'s football history is taught informally in every neighbourhood café.',
    'Young Egyptians grow up wanting to score like Salah for the national team.',
    'Egypt\'s coaching staff studies opponents for weeks before World Cup games.',
    'The Pharaohs\' set-piece routines have decided many AFCON nights.',
    'Egypt\'s full-backs often push high, reflecting club styles from the local league.',
    'National team call-ups can transform a domestic player\'s career overnight.',
    'Egypt\'s 1990 World Cup squad included stars of that Egyptian league era.',
    'Fans still debate the greatest Pharaohs XI of all time.',
    'Egypt\'s away kit is usually white — a nod to the national flag\'s middle stripe.',
    'The Pharaohs\' press conferences are major media events in Cairo.',
    'Egypt\'s football federation oversees clubs from Alexandria to Aswan.',
    'World Cup 2026 gave a new generation of fans their first Egypt knockout dream.',
    'Egypt\'s midfield engine room has often decided AFCON semi-finals.',
    'Goal celebrations after Pharaohs goals are among the loudest in Africa.',
    'Egypt\'s scouting network watches both European leagues and local talent.',
    'The national team\'s hotel camps become temporary fan pilgrimage sites.',
    'Egypt\'s football identity mixes continental pride with Cairo club loyalty.',
    'Every AFCON, Egypt start among the favourites because of history alone.',
    'The Pharaohs\' wall of sound in home stadiums intimidates visiting sides.',
    'Egypt\'s World Cup group stage points in 2026 showed resilience and grit.',
    'Salah\'s leadership style inspires younger Pharaohs in the dressing room.',
    'Egypt\'s football story is still being written with every tournament.',
  ]},
  { match: 'ahly', facts: [
    'Al Ahly have won more CAF Champions League titles than any African club.',
    'Al Ahly were founded on 24 April 1907 by a group of Egyptian students.',
    'The club\'s name "Al Ahly" means "The National" in Arabic.',
    'Ahly\'s Ultras Ahlawy create some of Africa\'s most famous tifos.',
    'Al Ahly have appeared at the FIFA Club World Cup multiple times.',
    'The Red Devils once went years without losing an Egyptian league title race.',
    'Ahly\'s museum in Cairo displays decades of trophies and memorabilia.',
    'Many Egyptian internationals began their careers in Ahly\'s academy.',
    'Al Ahly vs Wydad is a major CAF Champions League rivalry.',
    'Ahly\'s red kits are sold across Africa and the Middle East.',
    'The club has won the Egyptian Super Cup many times.',
    'Ahly\'s coaching history includes local legends and foreign tacticians.',
    'Cairo Derby week is the biggest sporting event on Egypt\'s calendar.',
    'Al Ahly\'s training ground develops both first-team and youth players.',
    'The club\'s motto and culture emphasise national pride and excellence.',
    'Ahly fans travel in huge numbers for CAF away nights.',
    'Al Ahly have beaten European sides at Club World Cup tournaments.',
    'The club\'s medical and sports science departments are among Egypt\'s best.',
    'Ahly\'s midfield legends include Aboutrika and Hossam Ashour.',
    'Winning the league is considered the minimum expectation by Ahly fans.',
    'Al Ahly\'s badge is one of the most recognised club crests in Africa.',
    'The club has dominated Egyptian football for stretches spanning decades.',
    'Ahly\'s youth teams regularly win national age-group championships.',
    'Matchday at Ahly feels like a carnival of red smoke and drums.',
    'Al Ahly have lifted the CAF Confederation Cup as well as the Champions League.',
    'The club\'s commercial deals reflect its status as Africa\'s biggest club brand.',
    'Ahly\'s strikers have topped Egyptian league scoring charts for years.',
    'Players often call wearing the Ahly shirt the pinnacle of Egyptian club football.',
    'Al Ahly\'s board and members\' culture is unique in Egyptian sport.',
    'The Red Devils\' European Club World Cup games draw huge TV audiences.',
    'Ahly have a fierce competitive edge even in friendlies and Super Cups.',
    'The club\'s history includes political and social chapters tied to Cairo life.',
    'Al Ahly\'s goalkeepers have been national-team starters for generations.',
    'Winning CAF gold is celebrated like a national holiday by Ahly fans.',
    'The club recruits talent from across Egypt and Africa.',
    'Ahly\'s set-piece coaches obsess over details before big derbies.',
    'Al Ahly\'s kit launches sell out quickly among Cairo supporters.',
    'The club\'s anthem is sung in stadiums from Alexandria to Aswan.',
    'Ahly\'s defenders are taught to win duels before anything else.',
    'Former Ahly stars often become coaches or pundits in Egypt.',
    'Al Ahly\'s social media reach dwarfs most African clubs.',
    'Derby losses hurt Ahly fans for weeks — wins are celebrated for months.',
    'The club\'s trophy room needs constant expansion after title runs.',
    'Ahly\'s academy graduates often move to Europe after breakthrough seasons.',
    'Al Ahly treat every CAF group match as a must-win.',
    'The Red Devils\' press is famous for hunting the ball high up the pitch.',
    'Ahly fans keep detailed mental scorecards of historic derby results.',
    'The club\'s kit men prepare multiple red shirts for every final.',
    'Al Ahly\'s Champions League nights light up Cairo\'s skyline with flares.',
    'Winning the Egyptian Cup still matters deeply to Ahly\'s identity.',
    'The club\'s rivalry with Zamalek dates back over a century.',
    'Ahly\'s foreign signings are judged instantly by the demanding crowd.',
    'Al Ahly\'s captain armband is a symbol of leadership in Egyptian football.',
    'The club\'s history books fill shelves in Cairo sports libraries.',
    'Ahly\'s wingers are taught to cut inside and shoot like club legends.',
    'A late Ahly winner in a derby becomes instant YouTube legend.',
    'The Red Devils\' warm-up songs shake the tunnel before kickoff.',
    'Al Ahly\'s community programmes reach schools across Greater Cairo.',
    'Every generation of Ahly fans claims their era had the best team.',
    'The club\'s CAF Super Cup wins add to an unmatched continental haul.',
    'Ahly\'s training sessions are closed when big matches approach.',
    'The Red Devils\' analytical staff track opponents\' every throw-in pattern.',
    'Al Ahly expect to compete for every trophy every season.',
    'Ahly\'s left-backs have produced assists that decided league titles.',
    'The club\'s museum tours are popular with visiting football tourists.',
    'Al Ahly\'s night games under the lights feel cinematic to first-time visitors.',
    'Winning away in CAF is treated as a badge of honour by Ahly squads.',
    'The Red Devils\' reserve team feeds the first XI in injury crises.',
    'Ahly fans paint murals of club legends on Cairo walls.',
    'Al Ahly\'s handshake with history happens every time they lift silverware.',
    'The club\'s kit colour never changes — red is non-negotiable.',
    'Ahly\'s midfield screens protect the back line in low blocks when needed.',
    'A Club World Cup goal by Ahly trends worldwide within minutes.',
    'The Red Devils\' dressing-room standards are famously strict.',
    'Al Ahly\'s season ticket culture binds families across generations.',
    'Every Ahly debutant feels the weight of 100+ years of expectation.',
  ]},
  { match: 'zamalek', facts: [
    'Zamalek were originally founded as Qasr El Nil Club before renaming.',
    'The White Knights\' all-white kit is one of Africa\'s most classic looks.',
    'Zamalek have won the CAF Champions League titles in their history.',
    'Shikabala is a modern cult hero for Zamalek supporters.',
    'Zamalek\'s ultras produce elaborate choreographies for derby nights.',
    'The club has lifted the Egyptian Premier League on multiple occasions.',
    'Zamalek\'s academy has produced skillful attacking midfielders for decades.',
    'Hassan Shehata played for Zamalek before becoming Egypt\'s legendary coach.',
    'The White Knights\' CAF Confederation Cup win in 2019 sparked huge celebrations.',
    'Zamalek fans call their club "the school of art" for stylish football.',
    'Cairo Derby losses and wins define seasons for Zamalek supporters.',
    'Zamalek have appeared at the FIFA Club World Cup after continental titles.',
    'The club\'s white and red crest is instantly known across Egypt.',
    'Zamalek\'s home nights fill the Cairo International Stadium with white shirts.',
    'Many Zamalek legends later coached the first team.',
    'The White Knights\' cup runs often produce giant-killing stories.',
    'Zamalek\'s fan chants echo across the Nile on derby day.',
    'The club values technical midfielders who can dictate tempo.',
    'Zamalek\'s rivalry with Ahly is older than many African nations\' football associations.',
    'White smoke and flags turn derby stands into a sea of white.',
    'Zamalek have won the Egyptian Cup in multiple eras.',
    'The club\'s history includes golden generations of the 1980s and beyond.',
    'Zamalek\'s wingers are encouraged to take on full-backs one-vs-one.',
    'A Zamalek title parade stops traffic across Cairo.',
    'The White Knights recruit talent from Upper Egypt and the Delta.',
    'Zamalek\'s goalkeepers have produced legendary derby saves.',
    'Club historians keep detailed archives of every major final.',
    'Zamalek\'s social base stretches from Cairo to the Gulf diaspora.',
    'The White Knights treat every CAF away trip as a statement of ambition.',
    'Zamalek\'s youth sides wear the same white pride as the first team.',
    'Derby week interviews with Zamalek players dominate Egyptian sports TV.',
    'The club\'s training ground culture emphasises loyalty and flair.',
    'Zamalek fans never forget historic comebacks against Ahly.',
    'White Knights midfield maestros are compared to past club artists.',
    'Zamalek\'s kit launches feature classic white with red accents.',
    'The club has produced Egyptian national-team captains.',
    'Zamalek\'s Confederation Cup nights brought continental glory back to the club.',
    'Supporters\' songs name-check decades of White Knights heroes.',
    'Zamalek\'s full-backs bomb forward in the club\'s best attacking sides.',
    'A late derby equaliser for Zamalek can silence half of Cairo — and ignite the other half.',
    'The White Knights\' medical staff work overtime during congested schedules.',
    'Zamalek expect to challenge for the league every season.',
    'Club legends return as guests of honour on big anniversary matches.',
    'Zamalek\'s press box fills early on Cairo Derby day.',
    'The White Knights\' away support is loud even in hostile stadiums.',
    'Zamalek\'s cup final appearances are part of Egyptian football folklore.',
    'Young Zamalek fans grow up learning derby chants before they can read.',
    'The club\'s crest appears on murals across Zamalek and Mohandessin.',
    'White Knights coaches rotate tactics between possession and counters.',
    'Zamalek\'s European Club World Cup games give fans rare global nights.',
    'The club\'s transfer windows are followed like national news.',
    'Zamalek\'s left wingers have created countless derby assists.',
    'White smoke after a Zamalek winner hangs over Cairo for hours — in memory at least.',
    'The club\'s hall of fame spans strikers, keepers, and creative No.10s.',
    'Zamalek\'s community outreach includes youth tournaments in Cairo.',
    'Every White Knights generation claims the "true" Zamalek style.',
    'The club\'s anthem blasts from cars across the city after big wins.',
    'Zamalek\'s defenders take special pride in clean sheets against Ahly.',
    'White Knights set pieces have decided Egyptian Cup finals.',
    'Zamalek\'s reserve players train hoping for one derby cameo.',
    'The club\'s history is intertwined with Cairo\'s cultural life.',
    'Zamalek fans debate greatest XI lineups late into the night.',
    'The White Knights\' night matches under floodlights look cinematic in white.',
    'Zamalek\'s CAF campaigns rebuild continental credibility season by season.',
    'A debut goal in a Zamalek shirt can make a player a lifelong idol.',
    'The club\'s kit men prepare pristine white shirts for every final.',
    'Zamalek\'s analytical staff study Ahly\'s patterns before every derby.',
    'White Knights captains speak for millions of supporters.',
    'Zamalek\'s season highlights reels are watched on repeat by fans abroad.',
    'The club refuses to treat any match against Ahly as "just another game".',
    'Zamalek\'s football school ethos values skill over pure athleticism.',
    'White Knights legends are cheered whenever they return to the stadium.',
    'Zamalek\'s modern squads mix local stars with African and foreign talent.',
    'A Zamalek league title ends years of waiting for long-suffering fans.',
    'The White Knights\' identity is white shirts, red pride, and Cairo soul.',
  ]},
  { match: 'pyramids', facts: [
    'Pyramids FC transformed Egyptian football\'s transfer market with big spending.',
    'The club\'s rise challenged the century-old Ahly–Zamalek duopoly narrative.',
    'Pyramids attracted foreign stars rarely seen in the Egyptian league before.',
    '30 June Stadium became a familiar fortress for Pyramids home nights.',
    'The club\'s branding leans into Egypt\'s ancient wonder imagery.',
    'Pyramids invested heavily in coaching staff and sports science.',
    'Top-four finishes became a realistic target after their investment surge.',
    'Pyramids\' CAF campaigns put the new club on the continental map.',
    'The club\'s training complex aims for European-level standards.',
    'Pyramids\' recruitment scouts watch both Africa and Europe.',
    'Fans of smaller clubs sometimes cheer Pyramids for breaking the old order.',
    'The club\'s modern kits stand out among traditional Egyptian designs.',
    'Pyramids\' ownership model differs from classic Egyptian members\' clubs.',
    'Big-money signings raised wages and expectations across the league.',
    'Pyramids\' press conferences draw national media attention.',
    'The club targets Egyptian internationals to boost credibility.',
    'Pyramids\' away kits often feature bold contemporary designs.',
    'Youth development became a focus after the initial star-signing phase.',
    'Pyramids\' matchday experience aims to feel premium and modern.',
    'The club\'s name instantly signals Egyptian identity worldwide.',
    'Pyramids have pushed Ahly and Zamalek in tight league title races.',
    'Continental nights give Pyramids fans new European-style atmospheres.',
    'The club\'s medical facilities support a heavy fixture schedule.',
    'Pyramids\' midfield signings often dictate their season ambitions.',
    'Social media growth helped Pyramids build a young fanbase quickly.',
    'The club\'s stadium nights feature modern lighting and presentation.',
    'Pyramids\' coaches rotate tactics to match expensive squad depth.',
    'Egyptian Cup runs are used to prove Pyramids belong among the elite.',
    'The club\'s scouting of African talent mirrors big European clubs.',
    'Pyramids\' rise is a case study in modern football investment in Africa.',
    'Home fans create new chants that did not exist a decade ago.',
    'Pyramids\' goal celebrations trend when they beat traditional giants.',
    'The club\'s commercial partners reflect its ambitious brand.',
    'Pyramids\' defenders are signed to match the pace of their attackers.',
    'League table pressure is constant because spending brings expectation.',
    'Pyramids\' academy graduates dream of breaking into the star-studded XI.',
    'CAF group-stage travel expands the club\'s continental footprint.',
    'Pyramids\' kit sales grew as the club climbed the table.',
    'The club\'s analytics team tracks expected goals like European sides.',
    'Pyramids\' night matches under Cairo lights feel like big-club football.',
    'Winning a first major trophy is the stated dream of many Pyramids fans.',
    'The club\'s foreign contingent must adapt quickly to Egyptian league intensity.',
    'Pyramids\' set-piece coaches work overtime in title-challenging seasons.',
    'Every win over Ahly or Zamalek is framed as proof of a new era.',
    'Pyramids\' bench strength can change games in the final 20 minutes.',
    'The club\'s branding appears on billboards across Greater Cairo.',
    'Pyramids\' pre-season tours aim to build international recognition.',
    'Local rivalries with Cairo clubs heat up every transfer window.',
    'Pyramids\' goalkeepers face high-pressure nights against title rivals.',
    'The club\'s story is still young compared with century-old Egyptian giants.',
    'Pyramids\' fans measure success by trophies, not just spending.',
    'A deep CAF run would cement Pyramids among Africa\'s new powers.',
    'The club\'s training intensity is designed to match European calendars.',
    'Pyramids\' wingers are signed for pace in transition attacks.',
    'Egyptian football historians already note Pyramids\' disruptive impact.',
    'The club\'s membership and supporter culture is still evolving.',
    'Pyramids\' coaching changes make headlines when results dip.',
    'A league title for Pyramids would rewrite Egyptian football\'s modern map.',
    'The club\'s identity mixes ancient symbols with modern ambition.',
    'Pyramids\' away days teach the new fanbase how to travel as a big club.',
    'Sports science recovery protocols keep expensive squads match-fit.',
    'Pyramids\' strikers are judged by goals against the traditional top two.',
    'The club\'s rise forced other teams to rethink recruitment budgets.',
    'Pyramids\' match programmes and presentation chase top-flight polish.',
    'Young Cairo fans sometimes choose Pyramids as their "third" club story.',
    'Continental qualification is now expected, not celebrated as a miracle.',
    'Pyramids\' board sets clear seasonal targets for coaches.',
    'The club\'s floodlit training sessions run late into Cairo nights.',
    'Pyramids\' story shows how investment can accelerate club timelines.',
    'Every season adds new chapters to Pyramids\' short but loud history.',
  ]},
  { match: 'ismaily', facts: [
    'Ismaily\'s 1969 CAF Champions League win is a landmark for canal-city football.',
    'The Yellow Dragons\' kit is one of the most distinctive in Egypt.',
    'Ismaily Stadium nights are famous for passionate local support.',
    'The club\'s golden era still inspires Ismailia schoolchildren.',
    'Ismaily produced players who starred for Egypt\'s national team.',
    'Canal derbies against Port Said sides carry special regional pride.',
    'Ismaily\'s yellow army travels well for Egyptian Cup ties.',
    'The club\'s history is taught as local folklore in Ismailia cafés.',
    'Ismaily\'s technical style historically favoured passing football.',
    'Big Cairo clubs treat trips to Ismailia as difficult away days.',
    'The Yellow Dragons\' museum pieces include continental winners\' medals.',
    'Ismaily\'s academy looks for clever midfielders and brave defenders.',
    'Matchday markets around the stadium sell yellow scarves and flags.',
    'Ismaily\'s cup giant-killings still get replayed on Egyptian sports shows.',
    'The club\'s identity is tied to the Suez Canal\'s working communities.',
    'Ismaily fans remember league title seasons with special anniversary events.',
    'Yellow smoke after a big win hangs over Ismailia\'s streets.',
    'The club\'s coaches often emphasise youth pathways over big spending.',
    'Ismaily\'s rivalry games raise the intensity across the canal zone.',
    'Historic CAF nights put Ismailia on Africa\'s football map.',
    'The Yellow Dragons\' anthem is sung on buses to away matches.',
    'Ismaily\'s left wingers have created legendary cup assists.',
    'Local newspapers cover Ismaily with the intensity of a capital club.',
    'The club\'s training ground develops canal-city talent first.',
    'Ismaily\'s goalkeepers are heroes after penalty shootout wins.',
    'Yellow Dragons legends return for charity matches in Ismailia.',
    'Ismaily\'s set pieces have decided tense relegation and title battles.',
    'The club\'s crest appears on walls across Ismailia neighbourhoods.',
    'Fans debate whether the 1960s–70s side was Egypt\'s most stylish.',
    'Ismaily\'s Egyptian Cup runs create festival atmospheres in the city.',
    'Away support in yellow is visible from the upper tiers of Cairo stadiums.',
    'The club values loyalty — long-serving players become local icons.',
    'Ismaily\'s midfield schools teach quick combination play.',
    'Canal weather and travel add unique challenges for visiting teams.',
    'Ismaily\'s youth teams wear yellow with the same pride as the first XI.',
    'A win over Ahly or Zamalek becomes city legend for years.',
    'The Yellow Dragons\' medical staff know every local player\'s history.',
    'Ismaily\'s transfer policy often prioritises Egyptian talent.',
    'Stadium drums start hours before big Ismaily kickoffs.',
    'The club\'s history books fill shelves in Ismailia sports clubs.',
    'Ismaily\'s full-backs historically overlapped to stretch Cairo defences.',
    'Yellow Dragons fans paint murals of the 1969 continental triumph.',
    'Ismaily\'s coaching tree includes former players turned managers.',
    'Cup semi-final nights empty Ismailia cafés onto the streets.',
    'The club\'s identity resists being overshadowed by Cairo giants.',
    'Ismaily\'s academy graduates dream of a national-team call-up.',
    'Yellow shirts in the stands create a unique visual in Egyptian football.',
    'Ismaily\'s late winners are celebrated with horns across the canal city.',
    'The club\'s community programmes support local schools and academies.',
    'Ismaily\'s history proves smaller cities can conquer Africa.',
    'Every generation of Yellow Dragons fans learns the 1969 story first.',
    'Ismaily\'s press conferences after derby wins are pure local joy.',
    'The club\'s kit men keep yellow shirts immaculate for finals.',
    'Ismaily\'s analytical approach has modernised while keeping club soul.',
    'Yellow Dragons captains speak for an entire canal community.',
    'Ismaily\'s away days to Alexandria create coastal football festivals.',
    'The club\'s long-term dream is another continental deep run.',
    'Ismaily\'s defenders take pride in frustrating star Cairo forwards.',
    'Yellow smoke and drums make Ismaily Stadium a tough venue.',
    'The club\'s story is yellow, proud, and rooted in Ismailia forever.',
  ]},
  { match: 'smouha', facts: [
    'Smouha SC represents Alexandria\'s modern football ambition.',
    'The club\'s coastal city setting gives home games a Mediterranean feel.',
    'Smouha Stadium nights draw crowds from across Alexandria.',
    'Developing young talent is central to Smouha\'s club philosophy.',
    'Alexandria derbies against other local sides are fiercely contested.',
    'Smouha\'s blue colours stand out in Egyptian Premier League kits.',
    'Cup upsets against Cairo giants are Smouha folklore.',
    'The club\'s academy feeds both the first team and bigger clubs.',
    'Alexandria\'s football culture mixes Smouha with historic city clubs.',
    'Smouha\'s training ground sits within a sporting club community.',
    'Consistent top-flight seasons built Smouha\'s modern reputation.',
    'The club\'s fans bring drums and coastal energy to every home match.',
    'Smouha\'s coaches often trust academy graduates in big games.',
    'Away trips from Alexandria to Cairo are long but well supported.',
    'Smouha\'s midfielders are taught to press high in transitions.',
    'Local media in Alexandria cover Smouha like a flagship club.',
    'The club\'s youth tournaments attract talent from the north coast.',
    'Smouha\'s goalkeepers have produced famous cup heroics.',
    'Blue smoke after a big win lights up Alexandria nights.',
    'Smouha\'s set-piece routines decide tight Premier League matches.',
    'The club\'s identity is Alexandrian first, national second.',
    'Smouha\'s full-backs push forward to stretch defensive blocks.',
    'Academy call-ups to Egypt youth teams are celebrated at the club.',
    'Smouha\'s medical staff manage congested midweek cup schedules.',
    'Fans debate Smouha\'s greatest cup nights in waterfront cafés.',
    'The club\'s kit launches feature blue with coastal design touches.',
    'Smouha\'s press box fills when Cairo giants visit Alexandria.',
    'A late Smouha winner against a title favourite becomes local legend.',
    'The club\'s community programmes reach Alexandria schools.',
    'Smouha\'s wingers thrive on the wider pitch spaces at home.',
    'Consistency in mid-table or higher is a modern Smouha goal.',
    'The club\'s captains often come from long-serving local players.',
    'Smouha\'s Egyptian Cup runs create city-wide anticipation.',
    'Alexandria\'s weather can surprise visiting Cairo teams.',
    'Smouha\'s scouting watches Delta and coastal youth leagues.',
    'Blue flags on Alexandria corniche appear after big victories.',
    'The club\'s history is shorter than Cairo giants but proudly local.',
    'Smouha\'s midfield engines cover huge distances every match.',
    'Youth coaches at Smouha emphasise technical receiving under pressure.',
    'The club\'s away support wears blue in hostile Cairo stands.',
    'Smouha\'s analytical staff track pressing triggers like modern sides.',
    'A clean sheet against Ahly or Zamalek is celebrated as a trophy.',
    'Smouha\'s strikers learn to finish quickly in counter attacks.',
    'The club\'s story is written match by match on the Mediterranean coast.',
    'Smouha\'s reserve team gives minutes to future first-team stars.',
    'Local sponsorships keep Smouha rooted in Alexandria business life.',
    'Smouha\'s night matches under lights look brilliant in blue.',
    'The club refuses to be just a stepping stone — it wants its own glory.',
    'Smouha\'s fans sing about Alexandria pride before every kickoff.',
    'Every Smouha academy graduate who makes the XI inspires the next wave.',
  ]},
  { match: 'gouna', facts: [
    'El Gouna FC bring Red Sea resort football to the Premier League map.',
    'Tourists sometimes discover Egyptian football for the first time at El Gouna.',
    'The club\'s coastal setting is unique among Egyptian top-flight sides.',
    'El Gouna Stadium sits near beaches and lagoons.',
    'Survival and stability in the Premier League have been core missions.',
    'The club\'s identity mixes sport with Red Sea tourism culture.',
    'El Gouna\'s squad often includes experienced Egyptian professionals.',
    'Home advantage includes travel fatigue for visiting Cairo teams.',
    'The club invests to avoid yo-yo seasons between divisions.',
    'El Gouna\'s matchdays feel different from dense Cairo derby chaos.',
    'Local Red Sea communities rally behind the team on weekends.',
    'El Gouna\'s kits often feature colours tied to sea and sun.',
    'The club\'s rise put El Gouna on national sports broadcasts.',
    'Cup ties at home give El Gouna a chance to shock bigger clubs.',
    'Training in resort conditions can aid recovery and preparation.',
    'El Gouna\'s recruitment balances budget with Premier League needs.',
    'Away fans enjoy rare football trips to the Red Sea coast.',
    'The club\'s story shows football expanding beyond the Nile Delta.',
    'El Gouna\'s coaches adapt tactics to squad limitations smartly.',
    'Community events link the club with resort residents and workers.',
    'El Gouna\'s goalkeepers face aerial balls in windy coastal games.',
    'Premier League status is celebrated as a town-wide achievement.',
    'The club\'s social media shows beaches alongside training clips.',
    'El Gouna\'s midfielders work hard to close spaces against giants.',
    'Relegation battles taught the club valuable survival lessons.',
    'El Gouna\'s academy ideas aim to find Upper Egypt and Red Sea talent.',
    'Night matches by the sea create memorable atmospheres.',
    'The club\'s board targets sustainable, not flashy, growth.',
    'El Gouna\'s away days to Cairo are long logistical operations.',
    'Fans paint the resort in club colours after big wins.',
    'El Gouna\'s set pieces are vital in low-scoring survival matches.',
    'The club represents a modern, place-based Egyptian football brand.',
    'El Gouna\'s medical staff manage heat and travel carefully.',
    'A cup giant-killing would define the club\'s highlight reel.',
    'El Gouna\'s defenders organise deep blocks against elite attacks.',
    'Local sponsorships connect hotels and tourism to the team.',
    'El Gouna\'s young players dream of Egypt youth call-ups.',
    'The club\'s identity is sun, sea, and hard-fought points.',
    'El Gouna\'s press coverage spikes when they host Ahly or Zamalek.',
    'Travel to El Gouna tests visiting teams\' professionalism.',
    'The club\'s kit men prepare for humid Red Sea conditions.',
    'El Gouna\'s captains often lead by defensive example.',
    'Every point in the Premier League is gold for a resort club.',
    'El Gouna\'s story adds geographic diversity to Egyptian football.',
    'Fans from Cairo sometimes adopt El Gouna as a holiday club.',
    'El Gouna\'s coaching staff studies opponents on limited resources.',
    'The club\'s future depends on smart recruitment and community support.',
    'El Gouna nights prove football thrives from the Nile to the Red Sea.',
    'A stable top-flight decade would cement El Gouna\'s legacy.',
    'The club\'s motto could be: small town, big Premier League heart.',
  ]},
  { match: 'ceramica', facts: [
    'Ceramica Cleopatra FC is one of Egypt\'s newest top-flight success stories.',
    'Corporate backing accelerated Ceramica\'s climb through the divisions.',
    'The Cleopatra name ties the club to Egypt\'s most famous queen.',
    'New Suez Stadium nights gave the club a modern home identity.',
    'Ceramica\'s rapid rise surprised traditional Egyptian football observers.',
    'Investment in players matched ambition to stay in the Premier League.',
    'The ceramics company link makes the club\'s branding unique.',
    'Ceramica\'s transfer activity is closely watched each window.',
    'Suez region fans gained another top-flight club to support.',
    'The club\'s modern structure differs from century-old members\' clubs.',
    'Ceramica aim to be more than a yo-yo promotion side.',
    'Coaching appointments signal the club\'s seriousness about staying up — and rising.',
    'Ceramica\'s kits blend corporate colours with Egyptian motifs.',
    'Young players see Ceramica as a path to Premier League minutes.',
    'Cup runs help the new club build national recognition.',
    'Ceramica\'s scouting looks for value signings and hungry talents.',
    'Matchday presentation aims for a polished, modern feel.',
    'The club\'s story is still being written season by season.',
    'Ceramica\'s defenders learn quickly against Ahly and Zamalek attacks.',
    'Suez Canal zone football culture welcomed the new identity.',
    'Ceramica\'s midfield signings often define their tactical shape.',
    'Media coverage grew as the club beat established sides.',
    'Ceramica\'s academy plans aim to reduce long-term transfer reliance.',
    'A first major trophy remains the dream for early supporters.',
    'Ceramica\'s medical and fitness staff support a pro calendar.',
    'Away fans notice Ceramica\'s organised travelling support growing.',
    'The club\'s board sets clear survival-then-climb objectives.',
    'Ceramica\'s wingers stretch games when chasing late goals.',
    'Sponsorship visibility helps fund the Premier League project.',
    'Ceramica\'s set pieces are practised as a primary scoring weapon.',
    'New club rivalries form naturally against nearby canal sides.',
    'Ceramica\'s goalkeepers face high-pressure debuts against giants.',
    'The Cleopatra branding stands out on Egyptian sports billboards.',
    'Ceramica\'s analysts use data to punch above traditional weight.',
    'Fan culture is young but energetic and growing.',
    'Ceramica\'s night matches introduce new rituals and chants.',
    'The club\'s rise mirrors wider corporate investment trends in Egypt.',
    'Ceramica\'s coaches rotate squads carefully across congested weeks.',
    'A deep Egyptian Cup run would accelerate the club\'s legend.',
    'Ceramica\'s full-backs are asked to defend and attack in equal measure.',
    'Local schools begin to adopt Ceramica as a first club for kids.',
    'Ceramica\'s press conferences teach new spokespeople club messaging.',
    'Every win against a historic giant validates the project.',
    'Ceramica\'s identity mixes industry, heritage, and ambition.',
    'The club\'s logistics for away trips professionalised quickly.',
    'Ceramica\'s strikers are judged by goals that keep the team up.',
    'Sports science recovery helps a thin squad survive spring.',
    'Ceramica\'s story inspires other new Egyptian football projects.',
    'Stability in the Premier League is already a major achievement.',
    'Ceramica Cleopatra want their name remembered for trophies, not just spending.',
  ]},
  { match: 'pharco', facts: [
    'Pharco FC\'s pharmaceutical backing gives unusual financial stability.',
    'Alexandria gained another Premier League voice with Pharco\'s rise.',
    'The club\'s name nods to Egypt\'s pharaonic heritage.',
    'Pharco play in one of Alexandria\'s historic football venues.',
    'Climbing divisions required patience and structured investment.',
    'Pharco\'s project shows industry brands entering Egyptian football.',
    'Local derby energy rises when Pharco face Smouha.',
    'The club focuses on building a sustainable top-flight squad.',
    'Alexandria fans enjoy more home Premier League options now.',
    'Pharco\'s recruitment mixes experience with hungry young players.',
    'Cup ties give Pharco national TV exposure beyond the league.',
    'The club\'s medical partners fit naturally with its pharma identity.',
    'Pharco\'s coaches emphasise organisation against richer clubs.',
    'Away days teach the new fanbase how to travel as a top-flight side.',
    'Pharco\'s kits introduce fresh colours to Alexandria\'s football scene.',
    'Youth pathways are part of the club\'s long-term plan.',
    'Pharco\'s midfielders cover ground to protect a compact defence.',
    'Point totals mid-table are celebrated as progress, not failure.',
    'The club\'s board measures success in stability first.',
    'Pharco\'s set pieces create rare chances against deep blocks.',
    'Alexandria\'s coastal winds affect Pharco\'s home matches too.',
    'Pharco\'s strikers train finishing in tight box spaces.',
    'Media in Alexandria now split coverage between multiple clubs.',
    'Pharco\'s rise added jobs and activity around the club.',
    'A famous cup upset would define Pharco\'s early history.',
    'Pharco\'s defenders organise zonal marks on corners carefully.',
    'Fan chants are still being invented by a young supporter base.',
    'Pharco\'s analytics help pick winnable matches to target.',
    'The club\'s identity is Alexandria plus modern corporate sport.',
    'Pharco\'s goalkeepers shout constantly to organise the back line.',
    'Training schedules balance league survival with cup ambition.',
    'Pharco\'s full-backs track runners diligently on the counter.',
    'Local businesses sponsor Pharco as a city pride project.',
    'Pharco\'s night matches add to Alexandria\'s sporting nightlife.',
    'Every season without relegation strengthens the club\'s foundations.',
    'Pharco\'s scouting watches Delta talent overlooked by Cairo giants.',
    'The club\'s story is young, ambitious, and coastal.',
    'Pharco\'s captains lead with work-rate more than celebrity.',
    'Sports science support reduces soft-tissue injuries in spring.',
    'Pharco\'s wingers stretch games when chasing equalisers.',
    'Community days introduce schoolkids to the Pharco shirt.',
    'Pharco\'s press team builds a professional club voice.',
    'A first major trophy remains a distant but motivating dream.',
    'Pharco\'s fixtures against Cairo clubs are measuring sticks.',
    'The club treats every Premier League point as precious.',
    'Pharco\'s reserves feed the first team during injury crises.',
    'Alexandria derbies give Pharco instant local meaning.',
    'Pharco\'s modern project sits beside historic Alexandrian football.',
    'Fans hope Pharco becomes a permanent Premier League name.',
    'Pharco FC proves new clubs can still break into Egypt\'s elite.',
  ]},
  { match: 'national bank', facts: [
    'National Bank of Egypt FC earned promotion to the Premier League in 2021.',
    'The club\'s link to NBE makes it institutionally unique in Egypt.',
    'Green branding reflects the bank\'s familiar corporate colours.',
    'NBE FC\'s promotion was celebrated by staff and football fans alike.',
    'Cairo\'s football calendar grew busier with another top-flight side.',
    'The club focuses on steady improvement rather than instant titles.',
    'Young Egyptians get first-team minutes that bigger clubs may not offer.',
    'NBE\'s project shows banks investing in sport and community.',
    'Home matches add another Cairo venue night to the league.',
    'NBE FC\'s coaches build organised, hard-working sides.',
    'Cup runs give the banking club rare national spotlight moments.',
    'The club\'s recruitment looks for character as much as skill.',
    'Premier League survival seasons taught valuable lessons.',
    'NBE fans are building traditions from a blank canvas.',
    'The club\'s green kits stand out in photo galleries of the league.',
    'Away trips across Egypt introduce NBE to regional football cultures.',
    'NBE\'s midfielders are asked to win second balls relentlessly.',
    'Institutional backing helps plan multi-year squad building.',
    'NBE FC\'s academy ideas aim to create a talent pipeline.',
    'A famous win over a giant would write the club\'s first legend.',
    'NBE\'s defenders stay compact against elite attacking tridents.',
    'Matchday presentation grows more polished each season.',
    'The club\'s board sets realistic seasonal objectives.',
    'NBE\'s set pieces are a primary route to precious goals.',
    'Green flags appear in Cairo stands as the fanbase grows.',
    'NBE\'s strikers train movement to exploit narrow spaces.',
    'Media coverage rises when NBE host Ahly or Zamalek.',
    'The club\'s identity mixes finance professionalism with football passion.',
    'NBE\'s goalkeepers organise loudly on crosses into the box.',
    'Sports science support helps a developing squad stay fit.',
    'NBE\'s full-backs track wide threats on counter attacks.',
    'Community programmes link the bank\'s social mission to the club.',
    'NBE\'s night matches under lights build new rituals.',
    'Every clean sheet against a top side is celebrated hard.',
    'NBE\'s scouting watches second-division gems carefully.',
    'The club\'s story starts with promotion — and aims higher.',
    'NBE\'s captains embody work-rate for younger teammates.',
    'Analytical prep helps NBE punch up on select matchdays.',
    'Fan chants evolve as supporters invent club folklore.',
    'NBE\'s wingers stretch tired defences late in games.',
    'Logistics for away travel professionalised after promotion.',
    'NBE\'s reserves give minutes to future first-team options.',
    'The club treats relegation battles as unacceptable long-term.',
    'NBE\'s press voice stays calm and institutional in tone.',
    'A cup semi-final would accelerate NBE\'s national profile.',
    'Green shirts in Cairo add diversity to the capital\'s football map.',
    'NBE FC measures success in stability, growth, and pride.',
    'The club\'s modern project sits among historic Cairo giants.',
    'Fans hope NBE becomes a permanent Premier League name.',
    'National Bank of Egypt FC proves institutions can build football clubs too.',
  ]},
  { match: 'masry', facts: [
    'Al Masry SC is Port Said\'s proud football flagship.',
    'The Green Eagles\' nickname fits their green kits perfectly.',
    'Port Said Stadium atmospheres are legendary in Egyptian football.',
    'Al Masry\'s fans are among the most passionate in the canal zone.',
    'Mediterranean Port Said gives Al Masry a unique coastal identity.',
    'Cup upsets against Cairo clubs are Green Eagles folklore.',
    'Al Masry\'s history stretches across decades of Egyptian league football.',
    'Away teams dread the noise of a full Port Said home night.',
    'The club\'s academy develops canal-city talent for the first team.',
    'Al Masry\'s rivalry energy spikes against other canal sides.',
    'Green smoke and flags turn the stands into a forest of colour.',
    'Al Masry\'s midfielders play with canal-city grit and pride.',
    'Local newspapers treat Al Masry like Port Said\'s second government.',
    'The club\'s cup runs empty cafés onto Port Said streets.',
    'Al Masry\'s defenders thrive in physical, high-intensity matches.',
    'Green Eagles legends are remembered in port-side murals.',
    'Al Masry\'s set pieces create chaos in crowded penalty areas.',
    'Travel to Port Said tests visiting teams\' focus and fitness.',
    'Al Masry\'s goalkeepers become heroes after derby shootouts.',
    'The club\'s identity is green, loud, and Mediterranean.',
    'Al Masry\'s wingers attack full-backs with direct running.',
    'Youth call-ups from Al Masry feed Egypt\'s national pathway.',
    'Port Said\'s football culture is inseparable from Al Masry.',
    'The club\'s anthem echoes across the harbour after big wins.',
    'Al Masry\'s captains speak for a fiercely loyal city.',
    'Cup semi-final nights become city festivals in Port Said.',
    'Al Masry\'s scouting watches Suez Canal youth leagues closely.',
    'Green shirts in away ends make Al Masry travel visible.',
    'The club values fighters who leave everything on the pitch.',
    'Al Masry\'s medical staff manage tough physical calendars.',
    'A league push into the top half energises the whole port.',
    'Al Masry\'s full-backs overlap when the Green Eagles dominate.',
    'Historic matches against Ahly and Zamalek fill every seat.',
    'Al Masry\'s press box crackles on canal derby day.',
    'The club\'s kit launches sell green across Port Said shops.',
    'Al Masry\'s late winners spark horns across the city.',
    'Community programmes keep Al Masry close to port neighbourhoods.',
    'Al Masry\'s analytical staff still respect old-school intensity.',
    'Every generation claims their Green Eagles side was the bravest.',
    'Al Masry\'s reserves feed the XI during injury crises.',
    'The club\'s story is written in green under Mediterranean lights.',
    'Al Masry\'s strikers live for headers from wide crosses.',
    'Away support from Port Said is famous for never going quiet.',
    'Al Masry\'s coaching tree includes local heroes turned managers.',
    'A deep CAF dream still motivates long-time Green Eagles fans.',
    'Al Masry\'s night matches look electric in green and white.',
    'The club refuses to be intimidated by Cairo reputations.',
    'Al Masry\'s folklore is smoke, sound, and stubborn pride.',
    'Port Said kids grow up wanting to wear the Green Eagles shirt.',
    'Al Masry SC remains a pillar of Egyptian football outside Cairo.',
  ]},
  { match: 'mokawloon', facts: [
    'Arab Contractors SC (Al Mokawloon) were founded in 1973.',
    'The club\'s construction-industry roots shape its working identity.',
    'Al Mokawloon play at the Arab Contractors Stadium in Cairo.',
    'Many Egyptian internationals passed through Mokawloon\'s ranks.',
    'The club has lifted domestic trophies in Egyptian football.',
    'Mokawloon\'s academy is respected for technical development.',
    'Green kits make Al Mokawloon easy to spot in league montages.',
    'Yo-yo seasons taught the club resilience between divisions.',
    'Cairo matches against bigger clubs are always competitive affairs.',
    'Al Mokawloon\'s coaches often trust academy graduates.',
    'The club\'s history includes surprise cup runs.',
    'Mokawloon fans value loyalty over glamorous spending.',
    'Arab Contractors\' stadium nights create intimate atmospheres.',
    'The club\'s midfield school emphasises control and grit.',
    'Al Mokawloon\'s defenders take pride in frustrating star forwards.',
    'Youth coaches at Mokawloon stress first touch and decision-making.',
    'The club\'s green army travels for important cup ties.',
    'Mokawloon\'s set pieces have decided tight Cairo matches.',
    'Former players often return as coaches or scouts.',
    'Al Mokawloon\'s identity is work, youth, and Cairo pride.',
    'The club punches above its budget against richer rivals.',
    'Mokawloon\'s goalkeepers learn early under high-pressure crosses.',
    'Community links to construction workers keep the club grounded.',
    'Al Mokawloon\'s wingers attack space on the counter.',
    'A famous cup giant-killing lives long in club memory.',
    'Mokawloon\'s captains lead quieter dressing rooms with standards.',
    'The club\'s medical staff stretch limited resources wisely.',
    'Al Mokawloon\'s scouting watches Cairo youth leagues closely.',
    'Green flags appear when Mokawloon push for promotion or survival.',
    'The club\'s story proves mid-sized Cairo sides still matter.',
    'Mokawloon\'s full-backs track runners with professional discipline.',
    'Academy call-ups to national youth teams are celebrated hard.',
    'Al Mokawloon\'s press coverage spikes on cup upset nights.',
    'The club treats every point against the top two as a statement.',
    'Mokawloon\'s reserves give minutes to future first-team names.',
    'Training ground culture emphasises honesty and hard running.',
    'Al Mokawloon\'s night matches under lights feel properly Cairo.',
    'Fans debate the club\'s greatest academy graduates for hours.',
    'Mokawloon\'s analytical prep helps upset favourites occasionally.',
    'The club\'s kit men keep green shirts ready for every cup round.',
    'Al Mokawloon\'s strikers live for scrappy box goals.',
    'A stable Premier League run rebuilds the club\'s modern reputation.',
    'Mokawloon\'s away days teach young players big-match focus.',
    'The club\'s folklore is green shirts and never-say-die nights.',
    'Al Mokawloon remain a respected name in Egyptian football education.',
    'Community tournaments keep Mokawloon visible in Cairo districts.',
    'The club\'s long-term dream is sustained top-flight relevance.',
    'Mokawloon\'s midfield engines cover box-to-box distances proudly.',
    'Every debutant feels the weight of the club\'s producer reputation.',
    'Arab Contractors SC stands for Cairo craft and football graft.',
  ]},
  { match: 'enppi', facts: [
    'ENPPI FC\'s petroleum-industry link shaped a unique club model.',
    'The club is famous across Egypt for its youth academy pipeline.',
    'ENPPI have won the Egyptian Premier League title.',
    'Petrosport Stadium is ENPPI\'s familiar home ground.',
    'Many national-team regulars graduated from ENPPI\'s system.',
    'The club often develops talent then sells to bigger Egyptian sides.',
    'ENPPI\'s model influenced how other clubs think about academies.',
    'Technical, youthful football is ENPPI\'s traditional trademark.',
    'CAF campaigns added continental chapters to ENPPI\'s story.',
    'The petroleum backing provides structure beyond matchday chaos.',
    'ENPPI\'s coaches trust teenagers in high-pressure league games.',
    'Academy showcases at ENPPI attract scouts from across Egypt.',
    'The club\'s midfield graduates are known for clean technique.',
    'ENPPI\'s set-piece coaches teach patterns early in youth teams.',
    'A title-winning ENPPI side is remembered as proof the model works.',
    'Petrosport nights feel like a factory of future stars.',
    'ENPPI\'s defenders learn positional play before physical duels.',
    'The club\'s medical pathways support growing adolescent athletes.',
    'ENPPI\'s wingers are coached to receive on the half-turn.',
    'National youth call-ups are a regular ENPPI celebration.',
    'The club\'s transfer fees help fund the next academy wave.',
    'ENPPI\'s analytical culture fits its reputation for smart football.',
    'Fans take pride when ENPPI beat richer, older clubs.',
    'The club\'s kit launches stay relatively classic and professional.',
    'ENPPI\'s full-backs are taught timing overlapping runs.',
    'Cup runs give academy kids rare TV moments.',
    'ENPPI\'s captains often come from long-serving graduates.',
    'Sports science at ENPPI protects young legs across seasons.',
    'The club\'s scouting network feeds the famous academy.',
    'ENPPI\'s night matches showcase Egypt\'s production-line football.',
    'A CAF group stage is treated as development under pressure.',
    'ENPPI\'s strikers learn movement from first-team coaches early.',
    'The petroleum identity appears in club branding and partners.',
    'ENPPI\'s reserves are unusually strong because of academy depth.',
    'Coaches across Egypt respect ENPPI\'s player education.',
    'The club\'s folklore is trophies built from youth, not just money.',
    'ENPPI\'s goalkeepers graduate with strong distribution skills.',
    'Matchday programmes sometimes highlight academy success stories.',
    'ENPPI\'s midfield screens protect high defensive lines.',
    'The club\'s long-term plan is perpetual talent renewal.',
    'ENPPI\'s away days test young debutants\' character.',
    'A league challenge from ENPPI always makes title races interesting.',
    'The club\'s press voice emphasises process over panic.',
    'ENPPI\'s set pieces remain a teaching tool from U17 to first team.',
    'Fans know an ENPPI win might feature three academy starters.',
    'The club\'s identity is petroleum green and youth gold.',
    'ENPPI\'s coaching tree spreads academy ideas across Egypt.',
    'Every sold graduate funds the next ENPPI generation.',
    'Petrosport remains a quiet giant of Egyptian player development.',
    'ENPPI FC proves smart structure can win Egyptian football.',
  ]},
  { match: 'future', facts: [
    'Future FC are among the newer names in Egypt\'s top flight.',
    'The club\'s name signals long-term ambition in Egyptian football.',
    'Future invest to stay competitive against historic giants.',
    'Modern club structures are part of Future\'s founding idea.',
    'Transfer windows see Future active in shaping each season\'s squad.',
    'The club blends experienced pros with emerging Egyptian talent.',
    'Future\'s fanbase is still growing match by match.',
    'Cup runs help Future write early club folklore.',
    'Coaching appointments show Future\'s intent to climb tables.',
    'The club\'s kits introduce fresh designs to league photo spreads.',
    'Future\'s midfield signings often define their tactical season.',
    'Away days teach a young supporter culture how to travel.',
    'Future\'s board sets clear targets for coaches each year.',
    'Sports science support aims to match bigger clubs\' recovery.',
    'A famous win over Ahly or Zamalek would define Future\'s rise.',
    'The club\'s academy ideas look beyond short-term results.',
    'Future\'s defenders organise compact blocks against elite attacks.',
    'Media coverage grows when Future challenge for European places — or CAF spots.',
    'Future\'s wingers stretch games in transition moments.',
    'Matchday presentation chases a modern, professional feel.',
    'Future\'s goalkeepers face steep learning curves against stars.',
    'Community outreach helps Future plant roots in local areas.',
    'The club\'s scouting watches value markets across Africa.',
    'Future\'s set pieces are practised as a primary scoring plan.',
    'Fan chants are invented in real time by a new generation.',
    'Future\'s full-backs balance attack with recovery runs.',
    'Every Premier League point builds the club\'s young history.',
    'Future\'s captains model professionalism for newer teammates.',
    'Analytical prep helps Future target winnable mid-table battles.',
    'The club\'s night matches start new floodlit traditions.',
    'Future\'s strikers are judged by goals that change seasons.',
    'Logistics for travel professionalised as the club settled up top.',
    'Future\'s reserves feed the XI through injury spells.',
    'A cup semi-final would accelerate Future\'s national profile.',
    'The club treats identity-building as seriously as tactics.',
    'Future\'s press voice stays ambitious without overclaiming.',
    'Sponsorships fund Future\'s climb toward consistency.',
    'Future\'s midfield engines cover huge distances proudly.',
    'Youth call-ups from Future validate the project\'s pathway.',
    'The club\'s story is short — and intentionally unfinished.',
    'Future\'s kit men prepare new shirts for every cup round.',
    'Fans hope Future becomes a permanent Premier League force.',
    'Future\'s coaching staff rotate squads across congested weeks.',
    'A first major trophy is the north star for early supporters.',
    'Future\'s identity mixes new ownership with Egyptian football passion.',
    'The club studies how Pyramids and others disrupted the old order.',
    'Future\'s away support grows louder each successful season.',
    'Training standards aim to match the club\'s forward-looking name.',
    'Future FC want history to remember them for more than being "new".',
    'Every season adds another brick to Future\'s foundation.',
  ]},
  { match: 'baladiyat', facts: [
    'Baladiyat El Mahalla represent El Mahalla El Kubra in the Nile Delta.',
    'El Mahalla is one of Egypt\'s great industrial and textile cities.',
    'The club\'s name means municipality — community football at its core.',
    'Baladiyat fans are famous for loyalty through every division.',
    'Delta derbies bring intense local rivalry and pride.',
    'The club\'s roots sit far from Cairo\'s spotlight — and proud of it.',
    'Textile industry history ties into El Mahalla\'s sporting culture.',
    'Baladiyat\'s home support can surprise visiting capital clubs.',
    'Community identity matters more than glossy branding here.',
    'The club develops local Delta talent for first-team minutes.',
    'Baladiyat\'s kits carry the colours of municipal pride.',
    'Matchdays in El Mahalla feel like town festivals.',
    'The club\'s history includes climbs and battles across Egypt\'s pyramid.',
    'Baladiyat coaches know every local pitch and youth coach.',
    'Away trips from the Delta are long — fans still travel.',
    'Baladiyat\'s midfielders play with industrial-city work-rate.',
    'Cup ties against giants bring the whole of El Mahalla together.',
    'The club\'s academy is a pathway out — and a reason to stay.',
    'Baladiyat\'s defenders thrive in physical, direct matches.',
    'Local newspapers cover Baladiyat with hometown intensity.',
    'The club\'s set pieces decide tense lower-league and cup nights.',
    'Baladiyat\'s goalkeepers become local heroes after penalty wins.',
    'Community programmes keep the club close to municipal life.',
    'Baladiyat\'s wingers attack space on quick counters.',
    'A famous giant-killing would echo across the Delta for decades.',
    'The club\'s captains speak for workers and families alike.',
    'Baladiyat\'s medical staff stretch resources with care.',
    'Youth call-ups from El Mahalla inspire the next street generation.',
    'The club\'s folklore is smoke, drums, and never giving up.',
    'Baladiyat\'s full-backs track runners with honest effort.',
    'Promotion pushes energise the entire textile city.',
    'Baladiyat\'s scouting watches nearby Delta villages closely.',
    'Night matches under lights feel huge in El Mahalla.',
    'The club values loyalty characters over temporary stars.',
    'Baladiyat\'s strikers live for scrappy, crowded-box goals.',
    'Fans paint murals of club colours across municipal walls.',
    'Baladiyat\'s press voice is local, proud, and direct.',
    'Every debutant from El Mahalla carries neighbourhood hopes.',
    'The club\'s story proves Egyptian football is bigger than Cairo.',
    'Baladiyat\'s reserves feed the XI when fixtures pile up.',
    'Training culture emphasises toughness and togetherness.',
    'Baladiyat\'s away end stays loud even in hostile stadiums.',
    'A deep cup run would rewrite the club\'s modern highlight reel.',
    'The club\'s identity is Delta, municipal, and fiercely loyal.',
    'Baladiyat\'s midfield engines cover box-to-box distances all night.',
    'Local sponsors keep Baladiyat rooted in El Mahalla business.',
    'The club\'s long-term dream is sustained higher-division football.',
    'Baladiyat kids grow up wanting to wear the municipal shirt.',
    'Every point on the road is celebrated like a derby win.',
    'Baladiyat El Mahalla stand for community football that never quits.',
  ]},
];

/** Global facts shown in Did You Know / rotating pool for all fans */
const GLOBAL_FOOTBALL_FACTS = [
  'The Cairo Derby between Ahly and Zamalek is often called one of the world\'s fiercest rivalries.',
  'Egypt\'s Premier League is one of the oldest and most-watched leagues in Africa.',
  'CAF Champions League nights turn Cairo into a festival of flares and drums.',
  'Egyptian fans are famous for choreographed ultras displays.',
  'Many European clubs scout Egyptian league matches for emerging talent.',
  'Ramadan schedules force Egyptian clubs to adapt training and kickoff times.',
  'Street football in Cairo produces creative close-control players.',
  'Alexandria, Port Said, and Ismailia each have distinct football cultures.',
  'Egyptian Cup finals can draw huge TV audiences nationwide.',
  'The Pharaohs\' AFCON record is a source of permanent national pride.',
  'World Cup summers pause ordinary life when Egypt are playing.',
  'Club museums in Cairo preserve kits, boots, and historic medals.',
  'Egyptian coaches who win AFCON become national celebrities overnight.',
  'Derby week newspaper front pages are often all football.',
  'Youth academies in Egypt compete fiercely for the best 12-year-olds.',
  'Away travel across Egypt can mean 8+ hour bus journeys for fans.',
  'Floodlit night matches create some of Africa\'s best photos.',
  'Egyptian referees handle some of the most intense atmospheres in world football.',
  'Goal music and drums rarely stop for 90 minutes in big Egyptian games.',
  'Local radio call phone-ins debate lineups until midnight.',
  'Shirt sales spike after every Pharaohs tournament goal.',
  'Egyptian football Twitter (and now X) never sleeps on derby day.',
  'Half-time tea and seeds are classic stadium snacks in Egypt.',
  'Many Egyptian internationals still return home in the off-season to train.',
  'Club anthems are taught to children before they learn club histories.',
  'Penalty shootouts at AFCON wrote chapters of Egyptian sporting myth.',
  'The Nile Delta produces tough, hard-running midfielders.',
  'Upper Egypt talent increasingly reaches Premier League clubs.',
  'Women\'s football in Egypt continues to grow alongside the men\'s game.',
  'Futsal halls in Cairo sharpen quick feet for future wingers.',
  'Egyptian kit designs often nod to pharaonic motifs and the flag.',
  'Club presidents in Egypt can become as famous as star players.',
  'Transfer deadline day is followed like a national event.',
  'Egyptian analysts use modern expected-goals models more each year.',
  'Historic stadiums still host matches beside newer venues.',
  'Fan photography of tifos circulates worldwide within minutes.',
  'Egyptian football podcasts dissect every Cairo Derby for days.',
  'National team camps empty club benches of star names.',
  'Local derbies outside Cairo still decide neighbourhood bragging rights.',
  'Egyptian football\'s future depends on academies as much as big spending.',
  'A last-minute winner in Egypt can empty entire apartment blocks onto balconies.',
  'Club legends become TV pundits and keep debates alive for decades.',
  'Egyptian players in Europe carry national hopes every weekend.',
  'CAF group draws are watched as carefully as World Cup pots.',
  'Egyptian football fashion — scarves, drums, flags — is part of the show.',
  'From Ahly to Baladiyat, every club writes a chapter of Egypt\'s game.',
  'The beautiful game in Egypt is red, white, gold — and endlessly loud.',
  'Facts like these are why Egyptian Football Facts exists — crazy facts, real football.',
  'Scroll, search a club, and save your favourites — there are hundreds more where these came from.',
  'Every Did You Know tap can surface another Egyptian football story.',
];
