window.FOOTBALL_VIDEOS = [
  {
    id: 'wa1',
    src: 'videos/reel-1.mp4',
    poster: 'logo.png',
    username: '@EgyptianFacts',
    avatar: 'logo.png',
    caption: 'Egyptian football moment',
    tags: '#Egypt #Football #Reels',
    baseLikes: 3200,
  },
  {
    id: 'wa2',
    src: 'videos/reel-2.mp4',
    poster: 'logo.png',
    username: '@Pharaohs',
    avatar: 'https://media.api-sports.io/football/teams/32.png',
    caption: 'Pharaohs on the pitch - pure passion',
    tags: '#Pharaohs #EgyptFootball',
    baseLikes: 2800,
  },
  {
    id: 'wa3',
    src: 'videos/reel-3.mp4',
    poster: 'logo.png',
    username: '@CairoFootball',
    avatar: 'logo.png',
    caption: 'Cairo football vibes — sent in by a fan!',
    tags: '#Cairo #Egypt #FootballFacts',
    baseLikes: 4100,
  },
  {
    id: 'v1',
    src: 'https://assets.mixkit.co/videos/preview/mixkit-soccer-player-dribbling-the-ball-4387-large.mp4',
    poster: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&h=900&fit=crop',
    username: '@Pharaohs',
    avatar: 'https://media.api-sports.io/football/teams/32.png',
    caption: 'Egypt training vibes before the big knockout match',
    tags: '#Egypt #Pharaohs #WorldCup',
    baseLikes: 12400,
  },
  {
    id: 'v2',
    src: 'https://assets.mixkit.co/videos/preview/mixkit-goalkeeper-making-a-save-1366-large.mp4',
    poster: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600&h=900&fit=crop',
    username: '@CairoDerby',
    avatar: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=100&h=100&fit=crop',
    caption: 'That save had the whole stadium on their feet! 🧤',
    tags: '#Goalkeeper #EgyptFootball',
    baseLikes: 8920,
  },
  {
    id: 'v3',
    src: 'https://assets.mixkit.co/videos/preview/mixkit-man-playing-soccer-5015-large.mp4',
    poster: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=600&h=900&fit=crop',
    username: '@AhlyFans',
    avatar: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=100&h=100&fit=crop',
    caption: 'Street football in Cairo - Red Devils energy',
    tags: '#AlAhly #Cairo #Football',
    baseLikes: 15600,
  },
  {
    id: 'v4',
    src: 'https://assets.mixkit.co/videos/preview/mixkit-football-players-warming-up-5013-large.mp4',
    poster: 'https://images.unsplash.com/photo-1508098682722-e99b77232b05?w=600&h=900&fit=crop',
    username: '@GroupG',
    avatar: 'https://media.api-sports.io/football/teams/32.png',
    caption: 'Warm-up before Egypt vs Australia — Round of 32 awaits!',
    tags: '#Egypt #Australia #WC2026',
    baseLikes: 21000,
  },
  {
    id: 'v5',
    src: 'https://assets.mixkit.co/videos/preview/mixkit-soccer-stadium-at-night-4389-large.mp4',
    poster: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=600&h=900&fit=crop',
    username: '@EgyptianFacts',
    avatar: 'logo.png',
    caption: 'Night football under the lights — Egyptian stadium atmosphere is unmatched.',
    tags: '#Stadium #Egypt #FootballFacts',
    baseLikes: 6780,
  },
];
